### ISSUE TITLE
airconnect errors in logs no devices on MacOS with 1.9.1 (libatomic1 library issue)

### ISSUE THREAD

**Issue by RezzZ** [1activegeek/docker-airconnect#74]
```[AirConnect-AIRUPNP] Launching AIRUPNP ...
[AirConnect-AIRUPNP] AIRUPNP_VAR is NOT present, launching with standard launch variables
/usr/bin/airupnp-docker: error while loading shared libraries: libatomic.so.1: cannot open shared object file: No such file or directory
[AirConnect-AIRUPNP] Launching AIRUPNP ...
[AirConnect-AIRUPNP] AIRUPNP_VAR is NOT present, launching with standard launch variables
/usr/bin/airupnp-docker: error while loading shared libraries: libatomic.so.1: cannot open shared object file: No such file or directory
```

this message keeps looping over and over (if no vars are used like the two below).
Devices do work (somehow macos decided to move them lower)

I start the docker with two vars:
```AIRUPNP_VAR```
and
```AIRCAST_VAR```

both with value
```-o S1,S3,S5,S9,S12,ZP80,ZP90,S15,ZP100,ZP120```

with that running the following messages loops every second:

```
[AirConnect-AIRUPNP] Launching AIRUPNP ...
[AirConnect-AIRUPNP] AIRUPNP_VAR is NOT present, launching with standard launch variables
/usr/bin/airupnp-docker: error while loading shared libraries: libatomic.so.1: cannot open shared object file: No such file or directory
[AirConnect-AIRCAST] Launching AIRCAST ...
[AirConnect-AIRCAST] AIRCAST_VAR is present, launching with custom launch variables: -o S1,S3,S5,S9,S12,ZP80,ZP90,S15,ZP100,ZP120
v1.8.3 (Feb  1 2024 @ 01:10:52)
See -t for license terms
Usage: [options]
  -b <ip|iface>network  address or interface to bind to
  -a <port>[:<count>]   set inbound port and range for RTP and HTTP
  -c <mp3[:<rate>]|aac[:<rate>]|flac[:0..9]|wav>        audio format send to player
  -v <0..1>             group MediaVolume factor
  -x <config file>      read config from file (default is ./config.xml)
  -i <config file>      discover players, save <config file> and exit
  -I                    auto save config at every network scan
  -N <format>           transform device name using C format (%s=name)
  -l <[rtp][:http][:f]> RTP and HTTP latency (ms), ':f' forces silence fill
  -r                    let timing reference drift (no click)
  -f <logfile>          write debug to logfile
  -p <pid file>         write PID in file
  -d <log>=<level>      set logging level, logs: all|raop|main|util|cast, level: error|warn|info|debug|sdebug
  -z                    daemonize
  -Z                    NOT interactive
  -k                    immediate exit on SIGQUIT and SIGTERM
  -t                    license terms
  --noflush             ignore flush command (wait for teardown to stop)

Build options: LINUX
```
no devices are visible.

when reverting back to 1.8.3 (1.9.0 and other versions are not available for docker?)
my devices are back but log still shows above error-loop except for the AIRUPNP part.

**Comment by Hukuma1** [comment]
Mine is very simple. I haven't touched it in years. Are the vars the logs talk about required?

```
services:
  airconnect:
    image: 1activegeek/airconnect
    restart: unless-stopped
    container_name: airconnect
    hostname: airconnect
    network_mode: host
    environment:
      - AIRCAST_VAR=-x /config.xml
      - PUID=$PUID
      - PGID=$PGID
    volumes:
      - $CONFIG/airconnect/config.xml:/config.xml
```

```
[AirConnect-AIRUPNP] Launching AIRUPNP ...
[AirConnect-AIRUPNP] AIRUPNP_VAR is NOT present, launching with standard launch variables
/usr/bin/airupnp-docker: error while loading shared libraries: libatomic.so.1: cannot open shared object file: No such file or directory
[AirConnect-AIRUPNP] Launching AIRUPNP ...
[AirConnect-AIRUPNP] AIRUPNP_VAR is NOT present, launching with standard launch variables
/usr/bin/airupnp-docker: error while loading shared libraries: libatomic.so.1: cannot open shared object file: No such file or directory
[AirConnect-AIRUPNP] Launching AIRUPNP ...
[AirConnect-AIRUPNP] AIRUPNP_VAR is NOT present, launching with standard launch variables
/usr/bin/airupnp-docker: error while loading shared libraries: libatomic.so.1: cannot open shared object file: No such file or directory
[AirConnect-AIRUPNP] Launching AIRUPNP ...
[AirConnect-AIRUPNP] AIRUPNP_VAR is NOT present, launching with standard launch variables
/usr/bin/airupnp-docker: error while loading shared libraries: libatomic.so.1: cannot open shared object file: No such file or directory
[AirConnect-AIRUPNP] Launching AIRUPNP ...
[AirConnect-AIRUPNP] AIRUPNP_VAR is NOT present, launching with standard launch variables
/usr/bin/airupnp-docker: error while loading shared libraries: libatomic.so.1: cannot open shared object file: No such file or directory
[15:12:59.406] handle_rtsp:374 [0x7fd054050210]: received SET_PARAMETER
[15:12:59.406] handle_rtsp:587 [0x7fd054050210]: responding:
RTSP/1.0 200 OK
Audio-Jack-Status: connected; type=analog
CSeq: 1167
```

```
root@nas:~# uname -a
Linux nas 6.12.43+deb12-amd64 #1 SMP PREEMPT_DYNAMIC Debian 6.12.43-1~bpo12+1 (2025-09-06) x86_64 GNU/Linux
```

**Comment by bierchitekt** [comment]
The problem is that the latest version gets pulled. And some of the latest versions need another lib to be installed. 

My Merge Request should fix this but it’s failing because it’s not in the same repo and so cannot login to docker

**Comment by 1activegeek** [comment]
Thanks for all the info and patience. Sorry been tied up and hadn't had time to get my head into maintenance mode on this. Since I don't use it much myself, jumping in/out of the code just takes a good couple hours of focus. 

also thank you @bierchitekt and cskeeters for the PRs. I've pushed a test to the dev branch, using the change from cskeeters which includes the new library. I'd rather go this route than switch to the static library option as I believe long ago I had issues doing it this way. I also noted the original dev actually didn't suggest using unless necessary.

Please all who've had issues - test out this `:dev` build of the image, and let me know how you make out. If it resolves easily enough, and I can validate on mine it doesn't break anything, I'll let it sit for a few days, then I'll push to master/latest.

**Comment by 1activegeek** [comment]
Good news, it looks good on my end. So shouldn't break status quo ... I hope. 

Please report back once you've had a chance to test the `:dev` build. 

Thanks again for your help!

**Comment by RezzZ** [comment]
i'm still getting the same message every second. Funny thing though, the timestamp at the end of the AIRCAST_VAR is present line remains the same. Not sure why it's looped every second...
the liberary message IS gone though, so thats good :).
edit: and the devices are back so it's not a breaking issue anymore. But it might generate a lot of logging which is not nice

<img width="1168" height="459" alt="Image" src="https://github.com/user-attachments/assets/ce4ce0b8-5a09-4a41-b32f-6682c5a38497" />

**Comment by bierchitekt** [comment]
Seems like the lib is removed from the project again:
https://github.com/philippe44/AirConnect/blob/master/CHANGELOG

So 1.9.2 is fixing this.

Wouldn't it make sense to include the version of airconnect in the docker-file? Then it's clear what version is used in the image.

**Comment by 1activegeek** [comment]
Update: I've tagged the original dev to see if he can push 1.9.2 which I believe should fully resolve this. No need to tack on more messages to bog him down on the issue linked - but just linked it for visibility. As soon as this updates, I'll manually dispatch the build job to resolve the issue.

**Comment by Hukuma1** [comment]
Looks like he pushed out `1.9.2`. Thank you both!

**Comment by RezzZ** [comment]
also for me, no issues any more in the logs :). thank you!
